[project]
name = "comfyui-generator-pack"
description = """Danbooru-based tags generator and conflict filter"""

version = "1.0.0"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = []

[project.urls]
Repository = "https://github.com/alchemine/comfyui-generator-pack"
"Bug Tracker" = "https://github.com/alchemine/comfyui-generator-pack/issues"

[tool.comfy]
PublisherId = "alchemine"
DisplayName = "ComfyUI-Generator-Pack"
Icon = ""
